### ISSUE TITLE
registry:pull fails because the "release" command does not exist

### ISSUE THREAD

**Issue by connorlanigan** [agco/dokku-registry#5]
Dokku version: 0.11.3
OS: Ubuntu 16.04.3 on Vagrant

When using the `registry:pull` command to deploy an image, the command fails after downloading as Dokku doesn't have the release command (anymore?). It seems like this might be caused by incompatible changes to the Dokku command line API, as this project's README lists as a requirement "dokku 0.4.0+" but Dokku is already at 0.11.3. Nevertheless it would be really cool to be able to still use this plugin, as it seems to exactly match my use case (and probably others').

```
vagrant@ubuntu-xenial:~$ dokku registry:pull my-new-demo-app tutum/hello-world
Using default tag: latest
latest: Pulling from tutum/hello-world
658bc4dc7069: Already exists 
a3ed95caeb02: Already exists 
af3cc4b92fa1: Already exists 
d0034177ece9: Already exists 
983d35417974: Already exists 
Digest: sha256:0d57def8055178aafb4c7669cbc25ec17f0acdab97cc587f30150802da8f8d85
Status: Image is up to date for tutum/hello-world:latest
 !     `release my-new-demo-app` is not a dokku command.
 !     See `dokku help` for a list of available commands.
```

**Comment by josegonzalez** [comment]
#4 should handle this.
